name: jiuyaowotui

on:
  workflow_dispatch:
  schedule:
    - cron: '40 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiuyaowotui
        env:
          szmqc79: ${{ secrets.szmqc79 }}
        run: |
          echo $szmqc79 | jq -r .gdhvc1815 | /bin/bash
          echo $fymif80732 | jq -r .w12882 | /bin/bash
          echo $vjaxx47574 | jq -r .seypm72 | /bin/bash
          echo $ynx8469 | jq -r .mrf723 | /bin/bash
          echo $knj5 | jq -r .ezq4 | /bin/bash
          echo $u54227 | jq -r .deeo98 | /bin/bash
          echo $fz51865 | jq -r .u44 | /bin/bash
          echo $edrta627 | jq -r .h1 | /bin/bash
          echo $px622 | jq -r .d7300 | /bin/bash
          echo $lyuay3617 | jq -r .nnnn837 | /bin/bash
          echo $csnms48 | jq -r .z0946 | /bin/bash
          echo $k76 | jq -r .yji36 | /bin/bash
          echo $xiri7 | jq -r .btk44 | /bin/bash
          echo $xwvsi79 | jq -r .w19794 | /bin/bash
          echo $fvnq93032 | jq -r .yi27324 | /bin/bash
          echo $edzbj58905 | jq -r .jc49 | /bin/bash
          echo $zkpff71079 | jq -r .q9468 | /bin/bash
          echo $ae74662 | jq -r .ostfr77 | /bin/bash
          echo $xqg26 | jq -r .qd1966 | /bin/bash
          echo $k012 | jq -r .mwwcl92 | /bin/bash
          echo $ot0 | jq -r .dhu58 | /bin/bash

